#!/bin/zsh

# cursor shapes for vim modes
function zle-keymap-select {
	case "$KEYMAP" in
		vicmd) echo -ne "$cursor_block" ;;
		viins|main) echo -ne "$cursor_beam" ;;
	esac
}
zle -N zle-keymap-select

function precmd {
	# set terminal title to current working directory
	print -Pn '\e]0;%~\a'
}

function preexec {
	# set terminal title to current command
	print -Pn "\e]0;$1\a"

	# reset cursor shape
	echo -ne "$cursor_beam"
}

zle-line-init() {
	# reset cursor shape
	echo -ne "$cursor_beam"
}
zle -N zle-line-init


## extr = EXTRactor for all kinds of archives
## usage: extr <file>
function extr()
{
	if [ -f $1 ] ; then
		case $1 in
			*.tar.bz2)	tar xjf $1	;;
			*.tar.gz)	tar xzf $1	;;
			*.bz2)		bunzip2 $1	;;
			*.rar)		unrar x $1	;;
			*.gz)		gunzip $1	;;
			*.tar)		tar xf $1	;;
			*.tbz2)		tar xjf $1	;;
			*.tgz)		tar xzf $1	;;
			*.zip)		unzip $1	;;
			*.Z)		uncompress $1	;;
			*.7z)		7z x $1		;;
			*.deb)		ar x $1		;;
			*.tar.xz)	tar xf $1	;;
			*.tar.zst)	unzstd $1	;;
			*)		echo "'$1' cannot be extracted via extr()" ;;
		esac
	else
		echo "'$1' is not a valid file"
	fi
}
