#!/bin/zsh

# history settings
setopt hist_expire_dups_first hist_reduce_blanks share_history hist_verify

# vim mode
bindkey -v
export KEYTIMEOUT=1
cursor_block='\e[1 q'
cursor_beam='\e[5 q'

# colors
autoload -Uz colors && colors

# disable rm * warning
setopt rm_star_silent

# disable eof marking %
# setopt PROMPT_CR
# setopt PROMPT_SP
# export PROMPT_EOL_MARK=''
