[cmd_duration]
disabled = true

[line_break]
disabled = true

[character]
success_symbol = "[=>](bold purple)"
error_symbol = "[X>](bold red)"
vicmd_symbol = "[V>](bold yellow)"

[directory]
read_only = " <read-only>"

[rust]
symbol = "R "
